create table if not exists public.coach_training_modules (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('Mental', 'Fizic', 'Tehnic')),
  title text not null,
  duration text not null,
  focus text not null,
  description text not null,
  steps jsonb not null default '[]'::jsonb check (jsonb_typeof(steps) = 'array'),
  exercise_type text,
  xp integer not null default 35 check (xp >= 0),
  is_active boolean not null default true,
  created_by uuid references public.profiles (user_id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists coach_training_modules_category_idx
  on public.coach_training_modules (category, is_active, created_at desc);

alter table public.coach_challenges
  add column if not exists duration text not null default '5-20 min',
  add column if not exists is_active boolean not null default true,
  add column if not exists schedule_every_days integer not null default 2 check (schedule_every_days >= 1),
  add column if not exists schedule_start_date date not null default current_date;

create table if not exists public.daily_training_content (
  date_key date primary key,
  mental_module_id bigint not null references public.coach_training_modules (id),
  physical_module_id bigint not null references public.coach_training_modules (id),
  technical_module_id bigint not null references public.coach_training_modules (id),
  challenge_id text references public.coach_challenges (id),
  generated_at timestamptz not null default timezone('utc', now()),
  generated_by uuid references public.profiles (user_id) on delete set null
);

create table if not exists public.daily_category_rotation (
  category text primary key,
  used_item_ids text[] not null default '{}'::text[],
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.pick_next_category_item(category_input text, candidates text[])
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  used_items text[];
  remaining_items text[];
  picked_item text;
  candidates_count integer := coalesce(array_length(candidates, 1), 0);
begin
  if candidates_count = 0 then
    return null;
  end if;

  select used_item_ids
  into used_items
  from public.daily_category_rotation
  where category = category_input
  for update;

  if not found then
    insert into public.daily_category_rotation (category, used_item_ids)
    values (category_input, '{}'::text[]);
    used_items := '{}'::text[];
  end if;

  select array_agg(candidate)
  into remaining_items
  from unnest(candidates) as candidate
  where not (candidate = any(coalesce(used_items, '{}'::text[])));

  if coalesce(array_length(remaining_items, 1), 0) = 0 then
    used_items := '{}'::text[];
    remaining_items := candidates;
  end if;

  picked_item := remaining_items[1 + floor(random() * array_length(remaining_items, 1))::integer];
  used_items := array_append(coalesce(used_items, '{}'::text[]), picked_item);

  update public.daily_category_rotation
  set
    used_item_ids = used_items,
    updated_at = timezone('utc', now())
  where category = category_input;

  return picked_item;
end;
$$;

create or replace function public.generate_daily_training_content(
  target_date date default current_date,
  force_regenerate boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_row public.daily_training_content%rowtype;
  mental_candidates text[];
  physical_candidates text[];
  technical_candidates text[];
  challenge_candidates text[];
  mental_pick text;
  physical_pick text;
  technical_pick text;
  challenge_pick text;
begin
  if not force_regenerate then
    select *
    into existing_row
    from public.daily_training_content
    where date_key = target_date;

    if found then
      return jsonb_build_object('ok', true, 'dateKey', target_date::text, 'alreadyGenerated', true);
    end if;
  end if;

  perform pg_advisory_xact_lock(hashtextextended('daily_training_content_' || target_date::text, 0));

  if not force_regenerate then
    select *
    into existing_row
    from public.daily_training_content
    where date_key = target_date;

    if found then
      return jsonb_build_object('ok', true, 'dateKey', target_date::text, 'alreadyGenerated', true);
    end if;
  end if;

  select array_agg(id::text order by id)
  into mental_candidates
  from public.coach_training_modules
  where category = 'Mental'
    and is_active;

  select array_agg(id::text order by id)
  into physical_candidates
  from public.coach_training_modules
  where category = 'Fizic'
    and is_active;

  select array_agg(id::text order by id)
  into technical_candidates
  from public.coach_training_modules
  where category = 'Tehnic'
    and is_active;

  if coalesce(array_length(mental_candidates, 1), 0) = 0 then
    raise exception 'Nu exista module active in categoria Mental.';
  end if;

  if coalesce(array_length(physical_candidates, 1), 0) = 0 then
    raise exception 'Nu exista module active in categoria Fizic.';
  end if;

  if coalesce(array_length(technical_candidates, 1), 0) = 0 then
    raise exception 'Nu exista module active in categoria Tehnic.';
  end if;

  mental_pick := public.pick_next_category_item('mental', mental_candidates);
  physical_pick := public.pick_next_category_item('physical', physical_candidates);
  technical_pick := public.pick_next_category_item('technical', technical_candidates);

  select array_agg(id::text order by id)
  into challenge_candidates
  from public.coach_challenges
  where is_active
    and target_date >= schedule_start_date
    and ((target_date - schedule_start_date) % schedule_every_days = 0);

  if coalesce(array_length(challenge_candidates, 1), 0) > 0 then
    challenge_pick := public.pick_next_category_item('challenge', challenge_candidates);
  else
    challenge_pick := null;
  end if;

  insert into public.daily_training_content (
    date_key,
    mental_module_id,
    physical_module_id,
    technical_module_id,
    challenge_id,
    generated_at,
    generated_by
  )
  values (
    target_date,
    mental_pick::bigint,
    physical_pick::bigint,
    technical_pick::bigint,
    challenge_pick,
    timezone('utc', now()),
    auth.uid()
  )
  on conflict (date_key) do update
  set
    mental_module_id = excluded.mental_module_id,
    physical_module_id = excluded.physical_module_id,
    technical_module_id = excluded.technical_module_id,
    challenge_id = excluded.challenge_id,
    generated_at = excluded.generated_at,
    generated_by = excluded.generated_by;

  return jsonb_build_object('ok', true, 'dateKey', target_date::text, 'alreadyGenerated', false);
end;
$$;

create or replace function public.fetch_daily_training_content(
  target_date date default current_date,
  force_regenerate boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data record;
begin
  perform public.generate_daily_training_content(target_date, force_regenerate);

  select
    dtc.date_key,
    jsonb_build_object(
      'id', mental.id,
      'category', mental.category,
      'title', mental.title,
      'duration', mental.duration,
      'focus', mental.focus,
      'description', mental.description,
      'steps', mental.steps,
      'exerciseType', mental.exercise_type,
      'xp', mental.xp,
      'accent', 'blue'
    ) as mental_module,
    jsonb_build_object(
      'id', physical.id,
      'category', physical.category,
      'title', physical.title,
      'duration', physical.duration,
      'focus', physical.focus,
      'description', physical.description,
      'steps', physical.steps,
      'xp', physical.xp,
      'accent', 'orange'
    ) as physical_module,
    jsonb_build_object(
      'id', technical.id,
      'category', technical.category,
      'title', technical.title,
      'duration', technical.duration,
      'focus', technical.focus,
      'description', technical.description,
      'steps', technical.steps,
      'xp', technical.xp,
      'accent', 'green'
    ) as technical_module,
    case
      when challenge.id is null then null
      else jsonb_build_object(
        'id', challenge.id,
        'title', challenge.title,
        'description', challenge.description,
        'target', challenge.target,
        'duration', challenge.duration,
        'xp', challenge.xp,
        'levelRequired', challenge.level_required,
        'difficulty', challenge.difficulty,
        'coachNote', challenge.coach_note,
        'rewardText', challenge.reward_text,
        'badge', challenge.badge
      )
    end as challenge_module
  into row_data
  from public.daily_training_content dtc
  join public.coach_training_modules mental on mental.id = dtc.mental_module_id
  join public.coach_training_modules physical on physical.id = dtc.physical_module_id
  join public.coach_training_modules technical on technical.id = dtc.technical_module_id
  left join public.coach_challenges challenge on challenge.id = dtc.challenge_id
  where dtc.date_key = target_date;

  return jsonb_build_object(
    'dateKey', row_data.date_key::text,
    'mental', row_data.mental_module,
    'physical', row_data.physical_module,
    'technical', row_data.technical_module,
    'challenge', row_data.challenge_module
  );
end;
$$;

alter table public.coach_training_modules enable row level security;
alter table public.daily_training_content enable row level security;
alter table public.daily_category_rotation enable row level security;

drop policy if exists "authenticated can read coach training modules" on public.coach_training_modules;
create policy "authenticated can read coach training modules"
on public.coach_training_modules
for select
to authenticated
using (true);

drop policy if exists "authenticated can add coach training modules" on public.coach_training_modules;
create policy "authenticated can add coach training modules"
on public.coach_training_modules
for insert
to authenticated
with check (true);

drop policy if exists "authenticated can read daily training content" on public.daily_training_content;
create policy "authenticated can read daily training content"
on public.daily_training_content
for select
to authenticated
using (true);

drop policy if exists "service role manages daily category rotation" on public.daily_category_rotation;
create policy "service role manages daily category rotation"
on public.daily_category_rotation
for all
to service_role
using (true)
with check (true);

insert into public.coach_training_modules (category, title, duration, focus, description, steps, exercise_type, xp)
select *
from (
  values
    (
      'Mental',
      'Respiratie de campion',
      '4 min',
      'Calm si incredere',
      'Respiri controlat si iti pregatesti mintea pentru antrenament.',
      jsonb_build_array('Respira 4 secunde', 'Tine 2 secunde', 'Expira 4 secunde', 'Repeta de 6 ori'),
      'Respirație',
      25
    ),
    (
      'Mental',
      'Vizualizare de joc',
      '3 min',
      'Concentrare',
      'Imagineaza-ti trei actiuni perfecte inainte de a incepe sesiunea.',
      jsonb_build_array('Preluare curata', 'Schimbare rapida de directie', 'Finalizare precisa', 'Repeta secventa de 3 ori'),
      'Vizualizare',
      25
    ),
    (
      'Mental',
      'Vocea campionului',
      '5 min',
      'Dialog pozitiv',
      'Iti setezi energia cu afirmatii scurte si puternice.',
      jsonb_build_array('Spune: Sunt pregatit', 'Spune: Sunt calm', 'Spune: Sunt rapid', 'Incepe cu zambet si curaj'),
      'Dialog pozitiv',
      25
    ),
    (
      'Fizic',
      'Motorul corpului',
      '7 min',
      'Postura si coordonare',
      'Pregatesti corpul pentru ritm, accelerare si reactie.',
      jsonb_build_array('Tehnica lenta', 'Repetare controlata', 'Viteza progresiva', 'Reactie si coordonare'),
      null,
      35
    ),
    (
      'Fizic',
      'Picioare rapide',
      '8 min',
      'Mecanica de alergare',
      'Ridici calitatea pasilor si a schimbarilor de directie.',
      jsonb_build_array('Tehnica lenta', 'Repetare', 'Viteza', 'Reactie la semnal'),
      null,
      35
    ),
    (
      'Fizic',
      'Echilibru de fotbalist',
      '6 min',
      'Stabilitate',
      'Lucrezi postura, controlul corpului si coordonarea.',
      jsonb_build_array('Tehnica lenta', 'Repetare', 'Viteza', 'Reactie si coordonare'),
      null,
      35
    ),
    (
      'Tehnic',
      'Atingeri de elita',
      '12 min',
      'Control apropiat',
      'Lucrezi atingeri dese, schimbari de directie si viteza.',
      jsonb_build_array('Repetare', 'Complexitate', 'Viteza', 'Provocare cognitiva'),
      null,
      45
    ),
    (
      'Tehnic',
      'Pasa si scanare',
      '11 min',
      'Pase si decizie',
      'Construiesti ritmul paselor si viteza de gandire.',
      jsonb_build_array('Repetare', 'Complexitate', 'Viteza', 'Provocare cognitiva'),
      null,
      45
    ),
    (
      'Tehnic',
      'Dublu control',
      '13 min',
      'Bal mastery',
      'Controlezi mingea in spatiu mic si cresti ritmul executiei.',
      jsonb_build_array('Repetare', 'Complexitate', 'Viteza', 'Provocare cognitiva'),
      null,
      45
    )
) as seed_data(category, title, duration, focus, description, steps, exercise_type, xp)
where not exists (select 1 from public.coach_training_modules);
