create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  username text not null unique check (char_length(username) between 2 and 24),
  avatar_id text not null default 'rocket',
  total_xp integer not null default 0 check (total_xp >= 0),
  unlocked_badges jsonb not null default '[]'::jsonb,
  consistency_reward_milestones integer[] not null default '{}'::integer[],
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create table if not exists public.training_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  date_key date not null,
  task_id text not null,
  task_title text not null,
  xp integer not null check (xp >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, date_key, task_id)
);

create index if not exists training_completions_user_date_idx
  on public.training_completions (user_id, date_key desc);

create table if not exists public.challenge_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  challenge_id text not null,
  title text not null,
  xp integer not null check (xp >= 0),
  badge jsonb not null,
  completed_on date not null default current_date,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, challenge_id)
);

create index if not exists challenge_completions_user_date_idx
  on public.challenge_completions (user_id, completed_on desc);

create table if not exists public.coach_quotes (
  id bigint generated by default as identity primary key,
  quote text not null unique,
  created_by uuid references public.profiles (user_id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.coach_challenges (
  id text primary key,
  title text not null,
  description text not null,
  target text not null,
  xp integer not null default 130 check (xp >= 0),
  level_required integer not null default 2 check (level_required >= 1),
  difficulty text not null default 'Coach Pick',
  coach_note text not null,
  reward_text text not null,
  badge jsonb not null,
  created_by uuid references public.profiles (user_id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    user_id,
    username,
    avatar_id
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'avatar_id', 'rocket')
  )
  on conflict (user_id) do update
  set
    username = excluded.username,
    avatar_id = excluded.avatar_id,
    updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create or replace function public.player_level(total_xp_input integer)
returns integer
language sql
immutable
as $$
  select case
    when total_xp_input >= 1500 then 7
    when total_xp_input >= 1120 then 6
    when total_xp_input >= 780 then 5
    when total_xp_input >= 500 then 4
    when total_xp_input >= 280 then 3
    when total_xp_input >= 120 then 2
    else 1
  end
$$;

create or replace function public.append_badge(existing_badges jsonb, badge_to_add jsonb)
returns jsonb
language plpgsql
immutable
as $$
begin
  if coalesce(existing_badges, '[]'::jsonb) @> jsonb_build_array(jsonb_build_object('id', badge_to_add ->> 'id')) then
    return coalesce(existing_badges, '[]'::jsonb);
  end if;

  return coalesce(existing_badges, '[]'::jsonb) || jsonb_build_array(badge_to_add);
end;
$$;

create or replace function public.current_training_streak(user_id_input uuid, anchor_date date default current_date)
returns integer
language plpgsql
stable
as $$
declare
  streak_value integer;
begin
  if not exists (
    select 1
    from public.training_completions
    where user_id = user_id_input
      and date_key = anchor_date
      and task_id <> 'session-bonus'
      and task_id not like 'consistency-%'
  ) then
    return 0;
  end if;

  with recursive streak(day_key, streak_length) as (
    select anchor_date, 1
    union all
    select day_key - 1, streak_length + 1
    from streak
    where exists (
      select 1
      from public.training_completions
      where user_id = user_id_input
        and date_key = streak.day_key - 1
        and task_id <> 'session-bonus'
        and task_id not like 'consistency-%'
    )
  )
  select max(streak_length) into streak_value
  from streak;

  return coalesce(streak_value, 0);
end;
$$;

create or replace function public.sync_profile_rewards(user_id_input uuid, anchor_date date default current_date)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_badges jsonb;
  current_milestones integer[];
  streak_value integer;
  drill_count integer;
  challenge_count integer;
  new_milestone integer;
begin
  select unlocked_badges, consistency_reward_milestones
  into current_badges, current_milestones
  from public.profiles
  where user_id = user_id_input
  for update;

  streak_value := public.current_training_streak(user_id_input, anchor_date);

  select count(*)
  into drill_count
  from public.training_completions
  where user_id = user_id_input
    and task_id <> 'session-bonus'
    and task_id not like 'consistency-%';

  select count(*)
  into challenge_count
  from public.challenge_completions
  where user_id = user_id_input;

  if streak_value >= 7 then
    current_badges := public.append_badge(
      current_badges,
      '{"id":"streak-keeper","label":"Streak Keeper","description":"Earned for hitting a 7-day training streak.","rarity":"Epic","accent":"gold"}'::jsonb
    );
  end if;

  if drill_count >= 20 then
    current_badges := public.append_badge(
      current_badges,
      '{"id":"drill-machine","label":"Drill Machine","description":"Earned for completing 20 training drills.","rarity":"Rare","accent":"blue"}'::jsonb
    );
  end if;

  if challenge_count >= 3 then
    current_badges := public.append_badge(
      current_badges,
      '{"id":"challenge-hunter","label":"Challenge Hunter","description":"Earned for completing 3 football challenges.","rarity":"Rare","accent":"orange"}'::jsonb
    );
  end if;

  new_milestone := floor(streak_value / 7);

  if new_milestone > 0 and not new_milestone = any(coalesce(current_milestones, '{}'::integer[])) then
    insert into public.training_completions (user_id, date_key, task_id, task_title, xp)
    values (user_id_input, anchor_date, 'consistency-' || new_milestone, '7-Day Consistency Bonus', 120)
    on conflict (user_id, date_key, task_id) do nothing;

    if found then
      update public.profiles
      set
        total_xp = total_xp + 120,
        consistency_reward_milestones = array_append(coalesce(current_milestones, '{}'::integer[]), new_milestone)
      where user_id = user_id_input;

      select consistency_reward_milestones into current_milestones
      from public.profiles
      where user_id = user_id_input;
    end if;
  end if;

  update public.profiles
  set unlocked_badges = current_badges
  where user_id = user_id_input;
end;
$$;

create or replace function public.complete_training_task(
  task_id_input text,
  task_title_input text,
  xp_input integer,
  training_date_input date,
  session_task_ids_input text[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  session_task_count integer;
begin
  if current_user_id is null then
    raise exception 'You must be logged in to save training progress.';
  end if;

  insert into public.training_completions (user_id, date_key, task_id, task_title, xp)
  values (current_user_id, training_date_input, task_id_input, task_title_input, xp_input)
  on conflict (user_id, date_key, task_id) do nothing;

  if not found then
    raise exception 'That drill is already completed for today.';
  end if;

  update public.profiles
  set total_xp = total_xp + xp_input
  where user_id = current_user_id;

  if not exists (
    select 1
    from public.training_completions
    where user_id = current_user_id
      and date_key = training_date_input
      and task_id = 'session-bonus'
  ) then
    select count(distinct task_id)
    into session_task_count
    from public.training_completions
    where user_id = current_user_id
      and date_key = training_date_input
      and task_id = any(session_task_ids_input);

    if session_task_count = coalesce(array_length(session_task_ids_input, 1), 0) and session_task_count > 0 then
      insert into public.training_completions (user_id, date_key, task_id, task_title, xp)
      values (current_user_id, training_date_input, 'session-bonus', 'Full Session Bonus', 60);

      update public.profiles
      set total_xp = total_xp + 60
      where user_id = current_user_id;
    end if;
  end if;

  perform public.sync_profile_rewards(current_user_id, training_date_input);

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.complete_challenge(
  challenge_id_input text,
  title_input text,
  xp_input integer,
  badge_input jsonb,
  completed_on_input date,
  level_required_input integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  current_total_xp integer;
  current_badges jsonb;
begin
  if current_user_id is null then
    raise exception 'You must be logged in to save challenge progress.';
  end if;

  select total_xp, unlocked_badges
  into current_total_xp, current_badges
  from public.profiles
  where user_id = current_user_id
  for update;

  if public.player_level(current_total_xp) < level_required_input then
    raise exception 'Reach level % to unlock this challenge.', level_required_input;
  end if;

  insert into public.challenge_completions (user_id, challenge_id, title, xp, badge, completed_on)
  values (current_user_id, challenge_id_input, title_input, xp_input, badge_input, completed_on_input)
  on conflict (user_id, challenge_id) do nothing;

  if not found then
    raise exception 'That challenge badge is already in your collection.';
  end if;

  update public.profiles
  set
    total_xp = total_xp + xp_input,
    unlocked_badges = public.append_badge(current_badges, badge_input)
  where user_id = current_user_id;

  perform public.sync_profile_rewards(current_user_id, completed_on_input);

  return jsonb_build_object('ok', true);
end;
$$;

alter table public.profiles enable row level security;
alter table public.training_completions enable row level security;
alter table public.challenge_completions enable row level security;
alter table public.coach_quotes enable row level security;
alter table public.coach_challenges enable row level security;

drop policy if exists "authenticated can read profiles" on public.profiles;
create policy "authenticated can read profiles"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "users can insert own profile" on public.profiles;
create policy "users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "authenticated can read training completions" on public.training_completions;
create policy "authenticated can read training completions"
on public.training_completions
for select
to authenticated
using (true);

drop policy if exists "authenticated can read challenge completions" on public.challenge_completions;
create policy "authenticated can read challenge completions"
on public.challenge_completions
for select
to authenticated
using (true);

drop policy if exists "authenticated can read coach quotes" on public.coach_quotes;
create policy "authenticated can read coach quotes"
on public.coach_quotes
for select
to authenticated
using (true);

drop policy if exists "authenticated can add coach quotes" on public.coach_quotes;
create policy "authenticated can add coach quotes"
on public.coach_quotes
for insert
to authenticated
with check (true);

drop policy if exists "authenticated can read coach challenges" on public.coach_challenges;
create policy "authenticated can read coach challenges"
on public.coach_challenges
for select
to authenticated
using (true);

drop policy if exists "authenticated can add coach challenges" on public.coach_challenges;
create policy "authenticated can add coach challenges"
on public.coach_challenges
for insert
to authenticated
with check (true);

insert into public.coach_quotes (quote)
values
  ('Champions improve when nobody is watching.'),
  ('Every clean touch today builds your confidence for tomorrow.'),
  ('Small spaces can create huge football skills.'),
  ('Effort is your superpower when practice feels hard.'),
  ('Train with focus and your game will shine on match day.'),
  ('Your weaker foot becomes stronger every brave attempt.')
on conflict (quote) do nothing;
